apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app.kubernetes.io/name: proxy
spec:
  containers:
  - name: nginx
    image: brian92292/argocd:28
    ports:
      - containerPort: 80
        name: http-web-svc


